### ISSUE TITLE
Lots of words are broken

### ISSUE THREAD

**Issue by antoineboquet** [Gaffiot/GaffiotApp#2]
Many definitions aren’t correctly  displayed for a while. The markup isn’t transformed, and there is sometimes huge sections of all caps text. For example see « facio », but many words with a substantial definition are affected.

**Comment by benoitfrisch** [comment]
Hi,
This issue is still under investigation, because the problem lies in the app database (See issue #1). In the meanwhile you can use[https://gaffiot.org](https://gaffiot.org).

**Comment by antoineboquet** [comment]
Thanks for your answer. For some reason I didn't see that my issue was the same as the other.
